### ISSUE TITLE
Removing a value from system variable Path

### ISSUE THREAD

**Issue by cristianbercu** [GsNSIS/EnVar#9]
I am not sure if this is an issue but one can add a value to System variables Path but cannot remove it.

It seems `DeleteValue` returns an exit code 5 when I try. Is there a place that describes what each exit code means and finally can this actually be done with EnVar?

**Comment by gilbertsoft** [comment]
Well, I'm using it successfully in a project, looks like you have a permission issue here, maybe the installer wasn't started elevated.

Here is my working example:
https://github.com/drud/ddev/blob/master/winpkg/ddev.nsi#L355-L357

**Comment by gilbertsoft** [comment]
@cristianbercu do you still need any help or can we close your issue?

**Comment by gilbertsoft** [comment]
Closing this issue because of no feedback.

**Comment by cristianbercu** [comment]
> Closing this issue because of no feedback.

Apologies, had some notifications on GH snoozed and I've just seen this. Starting with elevated permissions helped in my case. Also, thanks for sharing your working example.
